### ISSUE TITLE
consider adding parent_class_id to the class table

### ISSUE THREAD

**Issue by tylerljohnson** [benas/jcql#2]
Very interesting project, thanks for making it available.

Please consider adding a reference to the parent class in the class table, so that the inheritance hierarchy can be accessed from the data model.

**Comment by fmbenhassine** [comment]
Thank you!

There is already [two relations](https://github.com/benas/jcql/blob/master/jcql-core/src/main/resources/database.sql#L17) that are indexed:
- EXTENDS: allows you to see if a class/interface extends another class/interface
- IMPLEMENTS: allows you to determine if a class implements one or multiple interfaces

I think you can find the parent class with a query on EXTENDS table.

I'll add a more comprehensive description on the relational model.

**Comment by tylerljohnson** [comment]
Ah excellent... i hadn't made it through all the code, sorry for the oversight on my part.

**Comment by fmbenhassine** [comment]
No problem, that was hidden.. I'll update the documentation with all details asap!

**Comment by fmbenhassine** [comment]
I've added a note about currently implemented relations: https://github.com/benas/jcql#relations

More relations will be implemented progressively, stay tuned 😉
